name: CI Pipeline

on:
    pull_request:
        branches:
            - main
            - master
            - dev

    push:
        branches:
            - main
            - dev
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        env:
        PORT: 3001
        JWT_SECRET: test_jwt_secret
        REFRESH_SECRET: test_refresh_secret
        EMAIL_HOST: smtp.test.brevo.com
        EMAIL_PORT: 1025
        EMAIL_USER: test_user@smtp-brevo.com
        EMAIL_PASS: test_password
        TEST_MONGO_URI: mongodb://localhost:27017/test-db


        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install PNPM
              uses: pnpm/action-setup@v4
              with:
                  version: 8
            - name: Setup Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Install Dependencies
              run: pnpm install

            - name: Run Tests
              run: pnpm test

            - name: Run Linter
              run: pnpm run lint

            - name: Check Formatting
              run: pnpm run format

            - name: Build Project
              run: pnpm run build
